apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: SDXL-1.0
    serving.kserve.io/deploymentMode: RawDeployment
  name: sdxl
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: sdxl
      name: ''
      resources:
        limits:
          cpu: '6'
          memory: 24Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '4'
          memory: 16Gi
          nvidia.com/gpu: '1'
      runtime: kserve-sdxl
      args:
        - --single_file_model=/mnt/models/sd_xl_base_1.0.safetensors
        - --use_refiner=True
        - --refiner_single_file_model=/mnt/models/sd_xl_refiner_1.0.safetensors
        - --device=cuda
      storage:
        key: aws-connection-minio-shared
        path: /models/
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
