apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: kserve-sdxl
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    openshift.io/display-name: "Kserve for SDXL"
    opendatahub.io/template-display-name: "Kserve for SDXL"
    opendatahub.io/template-name: kserve-sdxl
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  multiModel: false
  builtInAdapter:
    modelLoadingTimeoutMillis: 90000
  supportedModelFormats:
    - name: sdxl
      autoSelect: true
  containers:
    - name: kserve-container
      image: quay.io/rh-aiservices-bu/kserve-sdxl:0.0.1
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm